# 常量
URL = ''
FILENAME = ''
SAVE_PATH = ''
GET_URL = ''
GET_JSON = ''
GET_INFORMATION = ''
GET_VERSION = ''
COOKIES_PATH = ''
PLAYER_NAME = ''
SECONDS = ''
HTTP_HOST = ''
HTTP_PORT = ''
SOCKS_HOST = ''
SOCKS_PORT = ''
SOCKS_USERNAME = ''
SOCKS_PASSWORD = ''
CMD = ''
STREAM_ID = ''

STREAM_DICT = {}
STREAM_DICT_VK = {}
STREAM_KEYS_LIST = []
STREAM_VALUES_LIST = []